// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreSqlExpressDB;

namespace NetCoreSqlExpressDB.Migrations
{
    [DbContext(typeof(SqlExpressDbConext))]
    partial class SqlExpressDbConextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBCommon.Entity1", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("P3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("P4")
                        .HasColumnType("float");

                    b.Property<double>("P5")
                        .HasColumnType("float");

                    b.Property<double>("P6")
                        .HasColumnType("float");

                    b.Property<DateTime>("P7")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("P8")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("P9")
                        .HasColumnType("datetime2");

                    b.Property<string>("RowNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table1");
                });

            modelBuilder.Entity("DBCommon.Entity2", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("P3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("P4")
                        .HasColumnType("float");

                    b.Property<double>("P5")
                        .HasColumnType("float");

                    b.Property<double>("P6")
                        .HasColumnType("float");

                    b.Property<DateTime>("P7")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("P8")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("P9")
                        .HasColumnType("datetime2");

                    b.Property<string>("RowNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table2");
                });

            modelBuilder.Entity("DBCommon.Entity3", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("P3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("P4")
                        .HasColumnType("float");

                    b.Property<double>("P5")
                        .HasColumnType("float");

                    b.Property<double>("P6")
                        .HasColumnType("float");

                    b.Property<DateTime>("P7")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("P8")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("P9")
                        .HasColumnType("datetime2");

                    b.Property<string>("RowNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table3");
                });

            modelBuilder.Entity("DBCommon.Entity4", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("P3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("P4")
                        .HasColumnType("float");

                    b.Property<double>("P5")
                        .HasColumnType("float");

                    b.Property<double>("P6")
                        .HasColumnType("float");

                    b.Property<DateTime>("P7")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("P8")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("P9")
                        .HasColumnType("datetime2");

                    b.Property<string>("RowNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table4");
                });

            modelBuilder.Entity("DBCommon.Entity5", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("P3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("P4")
                        .HasColumnType("float");

                    b.Property<double>("P5")
                        .HasColumnType("float");

                    b.Property<double>("P6")
                        .HasColumnType("float");

                    b.Property<DateTime>("P7")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("P8")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("P9")
                        .HasColumnType("datetime2");

                    b.Property<string>("RowNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table5");
                });
#pragma warning restore 612, 618
        }
    }
}
