// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharedFolderDBContext;

namespace SharedFolderDBContext.Migrations
{
    [DbContext(typeof(SharedFolderMultiTableNetCoreDBContext))]
    [Migration("20200117074212_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("RepositoryNetCore.Entity1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AName")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P3")
                        .HasColumnType("TEXT");

                    b.Property<double>("P4")
                        .HasColumnType("REAL");

                    b.Property<double>("P5")
                        .HasColumnType("REAL");

                    b.Property<double>("P6")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("P7")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P9")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Table1");
                });
#pragma warning restore 612, 618
        }
    }
}
