// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreSqliteDB;

namespace NetCoreSqliteDB.Migrations
{
    [DbContext(typeof(SqliteDBContext))]
    [Migration("20200206041634_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("DBCommon.Entity1", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P3")
                        .HasColumnType("TEXT");

                    b.Property<double>("P4")
                        .HasColumnType("REAL");

                    b.Property<double>("P5")
                        .HasColumnType("REAL");

                    b.Property<double>("P6")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("P7")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P9")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Table1");
                });

            modelBuilder.Entity("DBCommon.Entity2", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P3")
                        .HasColumnType("TEXT");

                    b.Property<double>("P4")
                        .HasColumnType("REAL");

                    b.Property<double>("P5")
                        .HasColumnType("REAL");

                    b.Property<double>("P6")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("P7")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P9")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Table2");
                });

            modelBuilder.Entity("DBCommon.Entity3", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P3")
                        .HasColumnType("TEXT");

                    b.Property<double>("P4")
                        .HasColumnType("REAL");

                    b.Property<double>("P5")
                        .HasColumnType("REAL");

                    b.Property<double>("P6")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("P7")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P9")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Table3");
                });

            modelBuilder.Entity("DBCommon.Entity4", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P3")
                        .HasColumnType("TEXT");

                    b.Property<double>("P4")
                        .HasColumnType("REAL");

                    b.Property<double>("P5")
                        .HasColumnType("REAL");

                    b.Property<double>("P6")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("P7")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P9")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Table4");
                });

            modelBuilder.Entity("DBCommon.Entity5", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P3")
                        .HasColumnType("TEXT");

                    b.Property<double>("P4")
                        .HasColumnType("REAL");

                    b.Property<double>("P5")
                        .HasColumnType("REAL");

                    b.Property<double>("P6")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("P7")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P9")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Table5");
                });
#pragma warning restore 612, 618
        }
    }
}
