// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiTablesNetCorDB;

namespace MultiTablesNetCorDB.Migrations
{
    [DbContext(typeof(NetCoreDBContext_5Tables))]
    partial class NetCoreDBContext_5TablesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("MultiTablesNetCorDB.Entity1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AName")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P3")
                        .HasColumnType("TEXT");

                    b.Property<double>("P4")
                        .HasColumnType("REAL");

                    b.Property<double>("P5")
                        .HasColumnType("REAL");

                    b.Property<double>("P6")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("P7")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P9")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Table1");
                });

            modelBuilder.Entity("MultiTablesNetCorDB.Entity2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AName")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P3")
                        .HasColumnType("TEXT");

                    b.Property<double>("P4")
                        .HasColumnType("REAL");

                    b.Property<double>("P5")
                        .HasColumnType("REAL");

                    b.Property<double>("P6")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("P7")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P9")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Table2");
                });

            modelBuilder.Entity("MultiTablesNetCorDB.Entity3", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AName")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P3")
                        .HasColumnType("TEXT");

                    b.Property<double>("P4")
                        .HasColumnType("REAL");

                    b.Property<double>("P5")
                        .HasColumnType("REAL");

                    b.Property<double>("P6")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("P7")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P9")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Table3");
                });

            modelBuilder.Entity("MultiTablesNetCorDB.Entity4", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AName")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P3")
                        .HasColumnType("TEXT");

                    b.Property<double>("P4")
                        .HasColumnType("REAL");

                    b.Property<double>("P5")
                        .HasColumnType("REAL");

                    b.Property<double>("P6")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("P7")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P9")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Table4");
                });

            modelBuilder.Entity("MultiTablesNetCorDB.Entity5", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AName")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P3")
                        .HasColumnType("TEXT");

                    b.Property<double>("P4")
                        .HasColumnType("REAL");

                    b.Property<double>("P5")
                        .HasColumnType("REAL");

                    b.Property<double>("P6")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("P7")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("P9")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Table5");
                });
#pragma warning restore 612, 618
        }
    }
}
